services:
  php:
    container_name: kalo-php
    build: 
      context: .
      dockerfile: ./docker/php.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-network

  server:
    container_name: kalo-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  db:
    container_name: kalo-mysql
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  redis:
    container_name: kalo-redis
    image: redis:alpine
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
